"use client"

import {
  RotateCcw,
  Check,
  AlertCircle,
  Settings,
  AlertTriangle,
} from "lucide-react"
import TagSelector from "@/components/shared/tag-selector/tag-selector"
import { documentFormStyles } from "./document-form.styles"
import type { DocumentFormProps } from "./document-form.props"

export default function DocumentForm({
  formData,
  errors,
  onInputChange,
  onTagsChange,
  isSlugAutoGenerated,
  onResetSlug,
}: DocumentFormProps) {
  return (
    <>
      {/* Title */}
      <div className={documentFormStyles.formSection}>
        <label htmlFor="title" className={documentFormStyles.inputLabel}>
          Document Title
        </label>
        <input
          type="text"
          id="title"
          value={formData.title}
          onChange={(e) => onInputChange("title", e.target.value)}
          className={
            errors.title
              ? documentFormStyles.textInputError
              : documentFormStyles.textInput
          }
          placeholder="Enter a compelling title for your document..."
        />
        {errors.title && (
          <p className={documentFormStyles.errorText}>
            <AlertCircle className={documentFormStyles.errorIcon} />
            {errors.title}
          </p>
        )}
      </div>

      {/* Slug */}
      <div className={documentFormStyles.formSection}>
        <div className={documentFormStyles.slugHeader}>
          <label htmlFor="slug" className={documentFormStyles.inputLabel}>
            URL Slug
          </label>
          <div className={documentFormStyles.slugBadgesContainer}>
            {/* Only show status badges when there's content to show status for */}
            {(formData.title || formData.slug) && (
              <>
                {isSlugAutoGenerated ? (
                  <span className={`${documentFormStyles.statusBadge} ${documentFormStyles.autoGeneratedBadge}`}>
                    <Check className={documentFormStyles.badgeIcon} />
                    Auto-generated
                  </span>
                ) : (
                  <span className={`${documentFormStyles.statusBadge} ${documentFormStyles.customBadge}`}>
                    <Settings className={documentFormStyles.badgeIcon} />
                    Custom
                  </span>
                )}
                {!isSlugAutoGenerated && formData.title && (
                  <button
                    type="button"
                    onClick={onResetSlug}
                    className={documentFormStyles.resetButton}
                    title="Reset to auto-generated slug"
                  >
                    <RotateCcw className={documentFormStyles.badgeIcon} />
                    Reset
                  </button>
                )}
              </>
            )}
          </div>
        </div>
        <div className={documentFormStyles.slugInputContainer}>
          <span className={documentFormStyles.slugPrefix}>/docs/</span>
          <input
            type="text"
            id="slug"
            value={formData.slug}
            onChange={(e) => {
              // Let the user type freely, only do basic cleanup
              const value = e.target.value.toLowerCase()
              onInputChange("slug", value)
            }}
            className={
              errors.slug
                ? documentFormStyles.slugInputError
                : documentFormStyles.slugInput
            }
            placeholder="url-friendly-slug"
          />
        </div>

        {/* Status and helper text */}
        <div className="space-y-2">
          {isSlugAutoGenerated && formData.title && (
            <p className={documentFormStyles.successMessage}>
              ✓ This URL is automatically generated from your title. Edit it to
              customize.
            </p>
          )}

          {!isSlugAutoGenerated && formData.title && (
            <p className={documentFormStyles.infoMessage}>
              ⚙️ You&apos;ve customized this URL. It won&apos;t change when you update the
              title.
            </p>
          )}

          {formData.slug && formData.slug.length > 50 && (
            <p className={documentFormStyles.warningMessage}>
              <AlertTriangle className={documentFormStyles.messageIcon} />
              Long URLs may be harder to remember and share. Consider
              shortening.
            </p>
          )}

          {formData.slug && !/^[a-z0-9-]+$/.test(formData.slug) && (
            <p className={documentFormStyles.errorMessage}>
              <AlertCircle className={documentFormStyles.messageIcon} />
              Use only lowercase letters, numbers, and hyphens for best SEO.
            </p>
          )}
        </div>

        {errors.slug && (
          <p className={documentFormStyles.errorText}>
            <AlertCircle className={documentFormStyles.errorIcon} />
            {errors.slug}
          </p>
        )}
      </div>

      {/* Description */}
      <div className={documentFormStyles.formSection}>
        <label htmlFor="description" className={documentFormStyles.inputLabel}>
          Description
        </label>
        <textarea
          id="description"
          rows={3}
          value={formData.description}
          onChange={(e) => onInputChange("description", e.target.value)}
          className={documentFormStyles.textarea}
          placeholder="Write a brief description for SEO and document previews..."
        />
        <p className={documentFormStyles.helperText}>
          This description will appear in search results and document previews.
        </p>
      </div>

      {/* Tags */}
      <div className={documentFormStyles.formSection}>
        <label className={documentFormStyles.inputLabel}>
          Tags
        </label>
        <p className={documentFormStyles.inputDescription}>
          Add tags to help organize and categorize your content
        </p>
        <TagSelector
          selectedTags={formData.tags || []}
          onTagsChange={onTagsChange}
          placeholder="Search or create tags..."
        />
      </div>

      {/* Content */}
      <div className={documentFormStyles.formSection}>
        <label htmlFor="content" className={documentFormStyles.inputLabel}>
          Content (Markdown)
        </label>
        <div className="relative">
          <textarea
            id="content"
            rows={20}
            value={formData.content}
            onChange={(e) => onInputChange("content", e.target.value)}
            className={
              errors.content
                ? documentFormStyles.contentTextareaError
                : documentFormStyles.contentTextarea
            }
            placeholder="# Your Document Title

Start writing your documentation here using Markdown syntax...

## Features
- Feature 1
- Feature 2

## Code Example
```javascript
console.log('Hello, World!');
```"
          />
          <div className={documentFormStyles.characterCounter}>
            {formData.content.length} characters
          </div>
        </div>
        {errors.content && (
          <p className={documentFormStyles.errorText}>
            <AlertCircle className={documentFormStyles.errorIcon} />
            {errors.content}
          </p>
        )}
      </div>
    </>
  )
}
