export const documentFormStyles = {
  // Form sections
  formSection: "bg-muted rounded-lg p-6",

  // Input styles
  inputLabel: "block text-sm font-semibold text-foreground mb-3",
  inputDescription: "text-sm text-muted-foreground mb-3",
  textInput:
    "w-full px-4 py-3 text-lg text-foreground border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-all bg-input",
  textInputError:
    "w-full px-4 py-3 text-lg text-foreground border border-destructive rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-all bg-destructive/5",
  textarea:
    "w-full px-4 py-3 text-foreground border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent bg-input resize-none",
  textareaError:
    "w-full px-4 py-3 text-foreground border border-destructive rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent bg-destructive/5 resize-none",
  contentTextarea:
    "w-full px-4 py-3 text-foreground border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent resize-y min-h-[500px] bg-input",
  contentTextareaError:
    "w-full px-4 py-3 text-foreground border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent resize-y min-h-[500px] bg-destructive/5",

  // Slug input styles
  slugInputContainer:
    "flex rounded-lg overflow-hidden border border-border focus-within:ring-2 focus-within:ring-ring focus-within:border-transparent",
  slugPrefix:
    "inline-flex items-center px-4 py-3 bg-muted text-muted-foreground text-sm font-medium border-r border-border",
  slugInput: "flex-1 px-4 py-3 text-foreground focus:outline-none bg-input",
  slugInputError: "flex-1 px-4 py-3 text-foreground focus:outline-none bg-destructive/5",

  // Helper text
  helperText: "mt-2 text-xs text-muted-foreground",
  characterCounter:
    "absolute bottom-3 right-3 text-xs text-muted-foreground bg-card px-2 py-1 rounded border border-border",

  // Error styles
  errorText: "mt-2 text-sm text-destructive flex items-center",
  errorIcon: "w-4 h-4 mr-1",
  
  // Slug section styles
  slugHeader: "flex items-center justify-between",
  slugBadgesContainer: "flex items-center space-x-2",
  
  // Status badges
  statusBadge: "inline-flex items-center px-2 py-1 rounded text-xs font-medium",
  autoGeneratedBadge: "bg-green-500/10 text-green-400",
  customBadge: "bg-primary/10 text-primary",
  badgeIcon: "w-3 h-3 mr-1",
  
  // Reset button
  resetButton: "inline-flex items-center px-2 py-1 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-muted rounded transition-colors cursor-pointer",
  
  // Helper messages
  successMessage: "text-xs text-green-400",
  infoMessage: "text-xs text-primary", 
  warningMessage: "text-xs text-yellow-400 flex items-center",
  errorMessage: "text-xs text-destructive flex items-center",
  messageIcon: "w-3 h-3 mr-1",
}