import { DocumentData, FormErrors } from "../document-editor.props"
import { Tag } from "@/types/tag"

export interface DocumentFormProps {
  formData: DocumentData
  errors: FormErrors
  onInputChange: (field: keyof DocumentData, value: string | null) => void
  onTagsChange: (tags: Tag[]) => void
  isSlugAutoGenerated: boolean
  onResetSlug: () => void
}