export const documentFormStyles = {
  // Form sections
  formSection: "bg-gray-50 rounded-lg p-6",

  // Input styles
  inputLabel: "block text-sm font-semibold text-gray-900 mb-3",
  inputDescription: "text-sm text-gray-600 mb-3",
  textInput:
    "w-full px-4 py-3 text-lg text-gray-900 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all bg-white",
  textInputError:
    "w-full px-4 py-3 text-lg text-gray-900 border border-red-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all bg-red-50",
  textarea:
    "w-full px-4 py-3 text-gray-900 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white resize-none",
  textareaError:
    "w-full px-4 py-3 text-gray-900 border border-red-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-red-50 resize-none",
  contentTextarea:
    "w-full px-4 py-3 text-gray-900 border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-y min-h-[500px] bg-white",
  contentTextareaError:
    "w-full px-4 py-3 text-gray-900 border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-y min-h-[500px] bg-red-50",

  // Slug input styles
  slugInputContainer:
    "flex rounded-lg overflow-hidden border border-gray-300 focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-transparent",
  slugPrefix:
    "inline-flex items-center px-4 py-3 bg-gray-100 text-gray-600 text-sm font-medium border-r border-gray-300",
  slugInput: "flex-1 px-4 py-3 text-gray-900 focus:outline-none bg-white",
  slugInputError: "flex-1 px-4 py-3 text-gray-900 focus:outline-none bg-red-50",

  // Helper text
  helperText: "mt-2 text-xs text-gray-500",
  characterCounter:
    "absolute bottom-3 right-3 text-xs text-gray-400 bg-white px-2 py-1 rounded border",

  // Error styles
  errorText: "mt-2 text-sm text-red-600 flex items-center",
  errorIcon: "w-4 h-4 mr-1",
  
  // Slug section styles
  slugHeader: "flex items-center justify-between",
  slugBadgesContainer: "flex items-center space-x-2",
  
  // Status badges
  statusBadge: "inline-flex items-center px-2 py-1 rounded text-xs font-medium",
  autoGeneratedBadge: "bg-green-100 text-green-800",
  customBadge: "bg-blue-100 text-blue-800",
  badgeIcon: "w-3 h-3 mr-1",
  
  // Reset button
  resetButton: "inline-flex items-center px-2 py-1 text-xs font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded transition-colors cursor-pointer",
  
  // Helper messages
  successMessage: "text-xs text-green-600",
  infoMessage: "text-xs text-blue-600", 
  warningMessage: "text-xs text-amber-600 flex items-center",
  errorMessage: "text-xs text-red-600 flex items-center",
  messageIcon: "w-3 h-3 mr-1",
}