export const slugInputStyles = {
  // Form section
  formSection: "bg-muted rounded-lg p-6",
  
  // Input styles
  inputLabel: "block text-sm font-semibold text-foreground mb-3",
  
  // Slug input styles
  slugInputContainer:
    "flex rounded-lg overflow-hidden border border-border focus-within:ring-2 focus-within:ring-ring focus-within:border-transparent",
  slugPrefix:
    "inline-flex items-center px-4 py-3 bg-muted text-muted-foreground text-sm font-medium border-r border-border",
  slugInput: "flex-1 px-4 py-3 text-foreground focus:outline-none bg-input",
  slugInputError: "flex-1 px-4 py-3 text-foreground focus:outline-none bg-destructive/5",
  
  // Slug section styles
  slugHeader: "flex items-center justify-between",
  slugBadgesContainer: "flex items-center space-x-2",
  
  // Status badges
  statusBadge: "inline-flex items-center px-2 py-1 rounded text-xs font-medium",
  autoGeneratedBadge: "bg-green-500/10 text-green-400",
  customBadge: "bg-primary/10 text-primary",
  badgeIcon: "w-3 h-3 mr-1",
  
  // Reset button
  resetButton: "inline-flex items-center px-2 py-1 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-muted rounded transition-colors cursor-pointer",
  
  // Helper messages
  successMessage: "text-xs text-green-400",
  infoMessage: "text-xs text-primary", 
  warningMessage: "text-xs text-yellow-400 flex items-center",
  errorMessage: "text-xs text-destructive flex items-center",
  messageIcon: "w-3 h-3 mr-1",
  
  // Error styles
  errorText: "mt-2 text-sm text-destructive flex items-center",
  errorIcon: "w-4 h-4 mr-1",
}