"use client"

import { AlertCircle, AlertTriangle, Check, RotateCcw, Settings } from "lucide-react"
import { useWatch, useController } from "react-hook-form"
import { generateSlug } from "@/lib/helpers"
import { slugInputStyles } from "./slug-input.styles"
import type { SlugInputProps } from "./slug-input.props"

export default function SlugInput({ 
  control
}: SlugInputProps) {
  // Watch both title and slug for auto-generation logic
  const [title, slug] = useWatch({
    control,
    name: ["title", "slug"],
  })

  const { field, fieldState } = useController({
    control,
    name: "slug",
  })

  // Calculate if slug is auto-generated
  const isAutoGenerated = () => {
    if (!title) return !slug
    return slug === generateSlug(title)
  }

  // Handle resetting slug to auto-generated value
  const handleResetSlug = () => {
    if (title) {
      field.onChange(generateSlug(title))
    }
  }
  return (
    <div className={slugInputStyles.formSection}>
      <div className={slugInputStyles.slugHeader}>
        <label htmlFor="slug" className={slugInputStyles.inputLabel}>
          URL Slug
        </label>
        <div className={slugInputStyles.slugBadgesContainer}>
          {/* Only show status badges when there's content to show status for */}
          {(title || slug) && (
            <>
              {isAutoGenerated() ? (
                <span
                  className={`${slugInputStyles.statusBadge} ${slugInputStyles.autoGeneratedBadge}`}
                >
                  <Check className={slugInputStyles.badgeIcon} />
                  Auto-generated
                </span>
              ) : (
                <span
                  className={`${slugInputStyles.statusBadge} ${slugInputStyles.customBadge}`}
                >
                  <Settings className={slugInputStyles.badgeIcon} />
                  Custom
                </span>
              )}
              {!isAutoGenerated() && title && (
                <button
                  type="button"
                  onClick={handleResetSlug}
                  className={slugInputStyles.resetButton}
                  title="Reset to auto-generated slug"
                >
                  <RotateCcw className={slugInputStyles.badgeIcon} />
                  Reset
                </button>
              )}
            </>
          )}
        </div>
      </div>
      
      <div className={slugInputStyles.slugInputContainer}>
        <span className={slugInputStyles.slugPrefix}>/docs/</span>
        <input
          type="text"
          id="slug"
          value={field.value || ""}
          onChange={(e) => {
            // Let the user type freely, only do basic cleanup
            const value = e.target.value.toLowerCase()
            field.onChange(value)
          }}
          className={
            fieldState.error
              ? slugInputStyles.slugInputError
              : slugInputStyles.slugInput
          }
          placeholder="url-friendly-slug"
        />
      </div>

      {/* Status and helper text */}
      <div className="space-y-2">
        {isAutoGenerated() && title && (
          <p className={slugInputStyles.successMessage}>
            ✓ This URL is automatically generated from your title. Edit it to
            customize.
          </p>
        )}

        {!isAutoGenerated() && title && (
          <p className={slugInputStyles.infoMessage}>
            ⚙️ You&apos;ve customized this URL. It won&apos;t change when you
            update the title.
          </p>
        )}

        {slug && slug.length > 50 && (
          <p className={slugInputStyles.warningMessage}>
            <AlertTriangle className={slugInputStyles.messageIcon} />
            Long URLs may be harder to remember and share. Consider
            shortening.
          </p>
        )}

        {slug && !/^[a-z0-9-]+$/.test(slug) && (
          <p className={slugInputStyles.errorMessage}>
            <AlertCircle className={slugInputStyles.messageIcon} />
            Use only lowercase letters, numbers, and hyphens for best SEO.
          </p>
        )}
      </div>

      {fieldState.error && (
        <p className={slugInputStyles.errorText}>
          <AlertCircle className={slugInputStyles.errorIcon} />
          {fieldState.error.message}
        </p>
      )}
    </div>
  )
}